name: Supabase Keep Alive

on:
  schedule:
    # Berjalan setiap hari pada jam 00:00 UTC
    - cron: '0 0 * * 6'
  workflow_dispatch: # Memungkinkan Anda menjalankan manual jika ingin tes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/courses" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
